### ISSUE TITLE
Move to Port Communication

### ISSUE THREAD

**Issue by igait-niu** [igait-niu/igait-backend#6]
Once we have completed development (meaning, this is a pre-production time issue), we remove our public API endpoint from AWS, and instead use intra-Docker Container port mappings to communicate. Then, the only semi-public API endpoint will be the one from Metis, which will be safely secured with an API key.

Do the following:
- [x] Remove old endpoint port-forwarding
- [x] Replace localhost with Docker Container IP aliasing
- [x] Add brute-forcing protection to the Metis endpoint for additional security

**Comment by hiibolt** [comment]
Obsolete issue - we handled this a few months ago via our decision to send results via email. Had we stuck with the idea of using a web API, this would still have been necessary.
